### ISSUE TITLE
concurrent map read and map write

### ISSUE THREAD

**Issue by prettynatty** [quickfixgo/quickfix#320]
Hello, sometime I receive concurrent read & write error when I try to log the whole struct or just a single value. I don't modify structs I received from quickfix, just read them.

```
fatal error: concurrent map read and map write

goroutine 51 [running]:
runtime.throw(0x497c353, 0x21)
	/usr/local/opt/go/libexec/src/runtime/panic.go:605 +0x95 fp=0xc4201d59b8 sp=0xc4201d5998 pc=0x402c9b5
runtime.mapaccess2_fast64(0x4857f80, 0xc420146960, 0x6, 0x1, 0x5f10028)
	/usr/local/opt/go/libexec/src/runtime/hashmap_fast.go:168 +0x1b7 fp=0xc4201d59e0 sp=0xc4201d59b8 pc=0x400e0e7
metabreak/vendor/github.com/quickfixgo/quickfix.FieldMap.GetField(0xc420146960, 0xc420074200, 0x16, 0x20, 0x498c898, 0x6, 0x5f10028, 0xc42019c1a0, 0x490d440, 0x1)
	/Users/wb/dev/go/src/metabreak/vendor/github.com/quickfixgo/quickfix/field_map.go:79 +0x48 fp=0xc4201d5a48 sp=0xc4201d59e0 pc=0x42391e8
metabreak/vendor/github.com/quickfixgo/quickfix.FieldMap.Get(0xc420146960, 0xc420074200, 0x16, 0x20, 0x498c898, 0x517fee0, 0xc42019c1a0, 0x0, 0x0)
	/Users/wb/dev/go/src/metabreak/vendor/github.com/quickfixgo/quickfix/field_map.go:68 +0xb8 fp=0xc4201d5ab0 sp=0xc4201d5a48 pc=0x4239108
metabreak/vendor/github.com/quickfixgo/fix44/executionreport.ExecutionReport.GetAvgPx(0xc420166270, 0xc4201662c0, 0xc420166298, 0xc420166270, 0xc4201a2329, 0x1, 0x0, 0x0)
	/Users/wb/dev/go/src/metabreak/vendor/github.com/quickfixgo/fix44/executionreport/ExecutionReport.generated.go:1165 +0x79 fp=0xc4201d5b10 sp=0xc4201d5ab0 pc=0x440a809
metabreak/fix.state.trade(0xc4200414d0, 0xc420076360, 0xc4200763c0, 0xc420076420, 0xc420076480)
	/Users/wb/dev/go/src/metabreak/fix/dumb.go:85 +0x807 fp=0xc4201d5fb8 sp=0xc4201d5b10 pc=0x46468f7
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4201d5fc0 sp=0xc4201d5fb8 pc=0x4059b91
created by metabreak/fix.Dumb
	/Users/wb/dev/go/src/metabreak/fix/dumb.go:59 +0x407
```

```
		case rep := <-s.execrep:
			clOrdID, _ := rep.GetClOrdID()
			avgPx, _ := rep.GetAvgPx()
			ordStatus, _ := rep.GetOrdStatus()
			netMoney, _ := rep.GetNetMoney() // here is dumb.85
			transactTime, _ := rep.GetTransactTime()
			rejectReason, _ := rep.GetOrdRejReason()
			execType, _ := rep.GetExecType()
```

It happens from time to time, in various places involving quickfix struct values reads.

**Comment by cbusbey** [comment]
Can you try re-running with the `-race` option?  This should help pinpoint where this is happening.

**Comment by zxwq** [comment]
@cbusbey hello, I also met this issue. 

I think the reason is that Maps are not safe for concurrent use.

type FieldMap struct {
	tagLookup map[Tag]field
	tagSort
}

**Comment by cbusbey** [comment]
Maps are not safe for concurrent use.  As FieldMaps are basically an embedded map, FieldMaps are also not safe for concurrent use.

**Comment by demget** [comment]
> 
> 
> Maps are not safe for concurrent use. As FieldMaps are basically an embedded map, FieldMaps are also not safe for concurrent use.

Then why not to fix this? Currently it's impossible to write asynchronous applications with this lib out of the box.

**Comment by juztin** [comment]
I'm also experiencing an intermittent panic around concurrent map access, but within `store.go`, line 99:

```
func (store memoryStore) GetMessages(beginSeqNum, endSeqNum int) ([][]byte, error) {
	var msgs [][]byte
	for seqNum := beginSeqNum; seqNum <= endSeqNum; seqNum++ {
		if m, ok := store.messageMap[seqNum]; ok {
			msgs = append(msgs, m)
		}
	}
	return msgs, nil
}
```

I just have a simple test `acceptor` that spits out the received messages to a table, and a test `initiator` that reads 1k messages from a raw FIX file, and pumps them onto the connection.

I'm not doing anything concurrent, just a line reader:

```
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		msg := quickfix.NewMessage()
		buf := bytes.NewBuffer(scanner.Bytes())
		err := quickfix.ParseMessage(msg, buf)
		checkErr(err)
		err = quickfix.Send(msg)
		checkErr(err)
	}
```

Simply adding in a delay ```<-time.After(5 * time.Millisecond)``` seems to give alleviate it.

**Comment by alonexy** [comment]
MarketDataIncrementalRefresh callback func There is a blocking problem

The data is delayed and cannot be processed concurrently.

Is there any good solution?
@cbusbey

**Comment by kleinerhund** [comment]
Ran into this today, had issues using the quickfix.Message after I had received it from a channel - still have to investigate what quickfix was is doing with the message after it is received in the FromApp(...) function.
Work around was to send a copy of the message like so.
```
original := newordersingle.New(...) // or wherever you get the message from

temp := new(quickfix.Message)
original.CopyInto(temp)
copy := newordersingle.FromMessage(temp)

outchan <- copy
```
✌️

**Comment by leith1972** [comment]
Essentially the same thing... I have encountered a concurrent map write on resendState.messageStash:

```
fatal error: concurrent map writes
goroutine 118 [running]:
github.com/quickfixgo/quickfix.inSession.processReject({{{}}}, 0xc0003ce400, 0xc000d9c2a0, {0x17c08c0?, 0xc000c49270?})
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/in_session.go:303 +0x229
github.com/quickfixgo/quickfix.inSession.FixMsgIn({{{}}}, 0xc0003ce400, 0xc000d9c2a0)
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/in_session.go:55 +0x225
github.com/quickfixgo/quickfix.resendState.FixMsgIn({{{}}, 0xc000e29f20, 0x0, 0x132}, 0xc0003ce400, 0xc000d9c2a0)
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/resend_state.go:44 +0x4d
github.com/quickfixgo/quickfix.(*stateMachine).fixMsgIn(0xc0003ce500, 0xc0003ce400, 0xc000fc9f08?)
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/session_state.go:106 +0x28
github.com/quickfixgo/quickfix.(*stateMachine).Incoming(0xc0003ce500, 0xc0003ce400, {0xc0005a0390?, {0x0?, 0x23e5760?, 0x23e5760?}})
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/session_state.go:99 +0x2f8
github.com/quickfixgo/quickfix.(*session).run(0xc0003ce400)
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/session.go:914 +0x386
github.com/quickfixgo/quickfix.(*Initiator).handleConnection.func1()
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/initiator.go:150 +0x25
created by github.com/quickfixgo/quickfix.(*Initiator).handleConnection in goroutine 117
        /go/pkg/mod/github.com/quickfixgo/quickfix@v0.9.6/initiator.go:149 +0xd3
goroutine 1 [select, 129 minutes]:
```

Not easily reproducible given the nature of the error.

I have encountered the same / similar errors in the past with other maps throughout the code. This is an occasional occurrence but very problematic when it arises.

How about mutex for updates / reads to this (and all) maps to make them safe for asynchronous code?
